# Docs:  http://about.travis-ci.org/docs/user/build-configuration/
# Scala: http://docs.travis-ci.com/user/languages/scala/
# Yaml:  http://yaml-online-parser.appspot.com/

sudo: false
language: scala
scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1
branches:
  only:
    - master
jdk:
  - oraclejdk8
env:
  - CODACY_PROJECT_TOKEN=a5c89dcf2b304b2ea4c8f72b4f593823
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt coverageReport
  - sbt coveralls
  - sbt codacyCoverage
notifications:
  email:
    - agilesteel@gmail.com
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
