# Docs:  http://about.travis-ci.org/docs/user/build-configuration/
# Scala: http://docs.travis-ci.com/user/languages/scala/
# Yaml:  http://yaml-online-parser.appspot.com/

sudo: false
language: scala
scala:
  - 2.10.6
  - 2.11.7
branches:
  only:
    - master
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coveralls
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage
notifications:
  email:
    - agilesteel@gmail.com
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
