package spells

trait SpellsModule
  extends AnsiModule
  with AnyOpsModule
  with CalendarOpsModule
  with ClearPrintModule
  with ClipboardModule
  with DateOpsModule
  with DurationOpsModule
  with ErrorPrintModule
  with HumanRenderingModule
  with MiscModule
  with SpellsConfig
  with StringOpsModule
  with StylePrint
  with TraversableOps
  with Tuple2Ops
  with XrayModule
