package spells

trait SpellsModule
  extends AnsiModule
  with AnyOpsModule
  with CalendarOpsModule
  with ClearPrintModule
  with ClipboardModule
  with CustomRenderingModule
  with DateOpsModule
  with DurationOpsModule
  with ErrorPrintModule
  with HumanRenderingModule
  with MiscModule
  with SpellsConfigModule
  with StackTraceElementModule
  with StringOpsModule
  with StylePrintModule
  with ThrowableOpsModule
  with TraversableOpsModule
  with Tuple2OpsModule
  with XrayModule
