package spells

trait Spells
  extends AnsiModule
  with AnyOpsModule
  with CalendarOpsModule
  with ClearPrintModule
  with ClipboardModule
  with DateOpsModule
  with DurationOpsModule
  with ErrorPrintModule
  with HumanRenderingModule
  with Misc
  with SpellsConfig
  with StringOps
  with StylePrint
  with TraversableOps
  with Tuple2Ops
  with XrayModule
